name: Publish release candidate to PyPI
uses: pypa/gh-action-pypi-publish@release/v1
on: 
  push:
    branches:
      - release-candidate
with:
    password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    repository_url: https://test.pypi.org/legacy/