name: Publish package to TestPyPI

on:
  push:
    branches:
      - release-candidate

jobs:
  publish:
    steps:
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
