name: Publish release to PyPI

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Test
        uses: ./.github/workflows/tests.yml
      - name: Set up Python 3.11
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.11'
      - name: Install in editable mode and build
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          python package.py --notests
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
